server:
  port: 9999

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: hello-service
            uri: lb://hello-service
            predicates:
              - Path=/hello/**
